const errorCodeMap = new Map();
//数据库
errorCodeMap.set("000000",{"cnErrorMsg":"查询失败","enErrorMsg":"","errorMsg":"查询失败","content":""});
errorCodeMap.set("000001",{"cnErrorMsg":"添加失败","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("000002",{"cnErrorMsg":"修改失败","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("000003",{"cnErrorMsg":"删除失败","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("000004",{"cnErrorMsg":"查询为空","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("000005",{"cnErrorMsg":"批量插入失败","enErrorMsg":"","errorMsg":"","content":""});
//网络
errorCodeMap.set("010000",{"cnErrorMsg":"网络连接不稳定,请稍后重试","enErrorMsg":"","errorMsg":"连接失败","content":""});
errorCodeMap.set("010001",{"cnErrorMsg":"网络连接不稳定,请稍后重试","enErrorMsg":"","errorMsg":"发送失败","content":""});
errorCodeMap.set("010002",{"cnErrorMsg":"网络连接不稳定,请稍后重试","enErrorMsg":"","errorMsg":"接收失败","content":""});
errorCodeMap.set("010003",{"cnErrorMsg":"网络连接不稳定,请稍后重试","enErrorMsg":"","errorMsg":"发送超时","content":""});
errorCodeMap.set("010004",{"cnErrorMsg":"网络连接不稳定,请稍后重试","enErrorMsg":"","errorMsg":"接收超时","content":""});
errorCodeMap.set("010005",{"cnErrorMsg":"网络连接不稳定,请稍后重试","enErrorMsg":"","errorMsg":"Feign调用失败","content":""});
errorCodeMap.set("010006",{"cnErrorMsg":"网络连接不稳定,请稍后重试","enErrorMsg":"","errorMsg":"Feign调用超时","content":""});
errorCodeMap.set("010007",{"cnErrorMsg":"网络连接不稳定,请稍后重试","enErrorMsg":"","errorMsg":"服务限流","content":""});
errorCodeMap.set("010008",{"cnErrorMsg":"网络连接不稳定,请稍后重试","enErrorMsg":"","errorMsg":"无法从服务注册中心获取服务信息","content":""});
errorCodeMap.set("010009",{"cnErrorMsg":"网络连接不稳定,请稍后重试","enErrorMsg":"","errorMsg":"发送信息失败","content":""});
errorCodeMap.set("0100010",{"cnErrorMsg":"网络连接不稳定,请稍后重试","enErrorMsg":"","errorMsg":"发送或接收异常","content":""});

//文件
errorCodeMap.set("020000",{"cnErrorMsg":"文件不存在","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("020001",{"cnErrorMsg":"文件夹不存在","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("020002",{"cnErrorMsg":"无法读取文件","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("020003",{"cnErrorMsg":"无法写文件","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("020004",{"cnErrorMsg":"保存文件失败","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("020005",{"cnErrorMsg":"文件名存在","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("020006",{"cnErrorMsg":"文件夹名存在","enErrorMsg":"","errorMsg":"","content":""});
//内存
errorCodeMap.set("030000",{"cnErrorMsg":"内存不足","enErrorMsg":"","errorMsg":"","content":""});
//参数
errorCodeMap.set("040000",{"cnErrorMsg":"参数为空","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("040001",{"cnErrorMsg":"参数不合法","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("040002",{"cnErrorMsg":"数据验证错误","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("040003",{"cnErrorMsg":"无参数更新","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("040004",{"cnErrorMsg":"id为空","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("040005",{"cnErrorMsg":"数据转换异常","enErrorMsg":"","errorMsg":"","content":""});
//业务
errorCodeMap.set("050000",{"cnErrorMsg":"用户已被邀请","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050001",{"cnErrorMsg":"用户已存在","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050002",{"cnErrorMsg":"暂无查看权限","enErrorMsg":"","errorMsg":"未授权","content":""});
errorCodeMap.set("050003",{"cnErrorMsg":"用户不存在","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050004",{"cnErrorMsg":"邀请码不存在","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050005",{"cnErrorMsg":"未知业务类型","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050006",{"cnErrorMsg":"转换微信支付的XML失败","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050007",{"cnErrorMsg":"解析XML异常","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050008",{"cnErrorMsg":"微信返回错误","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050009",{"cnErrorMsg":"无退款记录","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050010",{"cnErrorMsg":"用户未登录","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050011",{"cnErrorMsg":"验证码不正确","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050012",{"cnErrorMsg":"验证码失效或不存在","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050013",{"cnErrorMsg":"账户状态异常","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050014",{"cnErrorMsg":"静态化页面错误","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050015",{"cnErrorMsg":"用户未通过审核","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050016",{"cnErrorMsg":"授权信息已存在","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050017",{"cnErrorMsg":"设置商品类失败","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050018",{"cnErrorMsg":"设置商品失败","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050019",{"cnErrorMsg":"设置商品SPU属性失败","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050020",{"cnErrorMsg":"设置商品SKU属性失败","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050021",{"cnErrorMsg":"设置商品图片失败","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050022",{"cnErrorMsg":"设置门店商品失败","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050023",{"cnErrorMsg":"设置规格商品失败","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050024",{"cnErrorMsg":"设置商品套餐失败","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050025",{"cnErrorMsg":"获取商品码失败","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050026",{"cnErrorMsg":"商品、分类已关联","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050027",{"cnErrorMsg":"用户未关联商户","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050028",{"cnErrorMsg":"登录权限已过期","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050029",{"cnErrorMsg":"更新商户登录token失败","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050030",{"cnErrorMsg":"分类、打印机已关联","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050031",{"cnErrorMsg":"支付金额异常","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050032",{"cnErrorMsg":"无消费记录","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050033",{"cnErrorMsg":"退款时间已过期","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050034",{"cnErrorMsg":"退款金额异常","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050035",{"cnErrorMsg":"uuid重复","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050036",{"cnErrorMsg":"数据异常","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050037",{"cnErrorMsg":"登录失败","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050038",{"cnErrorMsg":"注册失败","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050039",{"cnErrorMsg":"重复消费","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050040",{"cnErrorMsg":"账户或密码错误","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050041",{"cnErrorMsg":"未知交易","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050042",{"cnErrorMsg":"交易金额不足","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050043",{"cnErrorMsg":"交易失败","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050044",{"cnErrorMsg":"订单不存在或失效","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050045",{"cnErrorMsg":"存在绑定关系","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050046",{"cnErrorMsg":"存在下级","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050047",{"cnErrorMsg":"名称重复","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050048",{"cnErrorMsg":"上传图片失败","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050049",{"cnErrorMsg":"绑定用户","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050050",{"cnErrorMsg":"商户配置信息不存在","enErrorMsg":"","errorMsg":"","content":""});
errorCodeMap.set("050051",{"cnErrorMsg":"抱歉，请重试","enErrorMsg":"","errorMsg":"获取微信小程序登录态失败","content":""});
errorCodeMap.set("050052",{"cnErrorMsg":"抱歉，请重试","enErrorMsg":"","errorMsg":"解密数据失败","content":""});
errorCodeMap.set("050053",{"cnErrorMsg":"抱歉,未能找到您搜索的内容","enErrorMsg":"","errorMsg":"ES查询失败","content":""});
errorCodeMap.set("050054",{"cnErrorMsg":"抱歉,未能找到您搜索的内容","enErrorMsg":"","errorMsg":"ES添加失败","content":""});
errorCodeMap.set("050055",{"cnErrorMsg":"抱歉,未能找到您搜索的内容","enErrorMsg":"","errorMsg":"ES修改失败","content":""});
errorCodeMap.set("050056",{"cnErrorMsg":"抱歉,未能找到您搜索的内容","enErrorMsg":"","errorMsg":"ES删除失败","content":""});
errorCodeMap.set("050057",{"cnErrorMsg":"抱歉,未能找到您搜索的内容","enErrorMsg":"","errorMsg":"ES查询为空","content":""});
errorCodeMap.set("050058",{"cnErrorMsg":"抱歉,未能找到您搜索的内容","enErrorMsg":"","errorMsg":"ES删除索引失败","content":""});
//未知错误
errorCodeMap.set("990000",{"cnErrorMsg":"网络连接不稳定，请稍后再试","enErrorMsg":"","errorMsg":"未知错误","content":""});

errorCodeMap.set("080002",{"cnErrorMsg":"用户未通过审核","enErrorMsg":"","errorMsg":"商户未授权","content":""});

export default {
    errorCodeMap
}